<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
		<RootNamespace>Journi.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="12.0.0" />
		<PackageReference Include="MediatR" Version="12.5.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.6" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Enums\" />
	  <Folder Include="Interfaces\" />
	  <Folder Include="Models\DTOs\" />
	  <Folder Include="Models\Entities\" />
	  <Folder Include="UseCases\" />
	</ItemGroup>
</Project>
