// <auto-generated />
using System;
using Journi.CodingChallenge.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Journi.CodingChallenge.Infrastructure.Migrations
{
    [DbContext(typeof(CodingChallengeDbContext))]
    [Migration("20260411222958_Initialise")]
    partial class Initialise
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Journi.CodingChallenge.Core.Models.Entities.Headphone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BatteryLife")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Mic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiseCancellationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Wireless")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Headphones");

                    b.HasData(
                        new
                        {
                            Id = new Guid("51f2e82c-69af-48b4-8d10-98bc5253ef3b"),
                            BatteryLife = "N/A",
                            Color = "Black",
                            Description = "Highly regarded closed-back studio headphones known for their detailed sound reproduction and comfortable fit.",
                            ImageFileName = "Beyerdynamic_DT_770_Pro.webp",
                            Manufacturer = "Beyerdynamic",
                            Mic = false,
                            Name = "Beyerdynamic DT 770 Pro",
                            NoiseCancellationType = "None",
                            Price = 179m,
                            Type = "Over-Ear",
                            Weight = "270 grams",
                            Wireless = false
                        },
                        new
                        {
                            Id = new Guid("55c6b66e-2550-4490-bbfb-2bb2d26cfa99"),
                            BatteryLife = "Up to 20 hours",
                            Color = "Silver",
                            Description = "Sleek design, exceptional noise cancellation, and impressive sound quality make these headphones a favorite among travelers and music enthusiasts.",
                            ImageFileName = "Bose_Noise_Cancelling_Headphones_700.jpg",
                            Manufacturer = "Bose",
                            Mic = true,
                            Name = "Bose Noise Cancelling Headphones 700",
                            NoiseCancellationType = "Adaptive Noise Cancellation",
                            Price = 379.95m,
                            Type = "Over-Ear",
                            Weight = "250 grams",
                            Wireless = true
                        },
                        new
                        {
                            Id = new Guid("73912724-86c8-440a-b668-de62757a649e"),
                            BatteryLife = "N/A",
                            Color = "Black",
                            Description = "Professional closed-back studio headphones with accurate sound reproduction, foldable design, and ergonomic fit.",
                            ImageFileName = "AKG_K371.webp",
                            Manufacturer = "AKG",
                            Mic = false,
                            Name = "AKG K371",
                            NoiseCancellationType = "None",
                            Price = 149m,
                            Type = "Over-Ear",
                            Weight = "255 grams",
                            Wireless = false
                        },
                        new
                        {
                            Id = new Guid("80281daf-321d-4d5e-90d4-7c86a41658c1"),
                            BatteryLife = "Up to 30 hours",
                            Color = "Beige",
                            Description = "Industry-leading noise cancellation, comfortable ear pads, and long battery life make these headphones a top choice for audiophiles.",
                            ImageFileName = "Sony_WH-1000XM4.webp",
                            Manufacturer = "Sony",
                            Mic = true,
                            Name = "Sony WH-1000XM4",
                            NoiseCancellationType = "Active Noise Cancellation",
                            Price = 349.99m,
                            Type = "Over-Ear",
                            Weight = "254 grams",
                            Wireless = true
                        },
                        new
                        {
                            Id = new Guid("82ff5cf5-5fc7-4e10-9837-29f3298c5818"),
                            BatteryLife = "Up to 36 hours",
                            Color = "Black",
                            Description = "Comfortable over-ear headphones with excellent noise cancellation, long battery life, and customizable sound profiles.",
                            ImageFileName = "Jabra_Elite_85h.jpg",
                            Manufacturer = "Jabra",
                            Mic = true,
                            Name = "Jabra Elite 85h",
                            NoiseCancellationType = "Hybrid Active Noise Cancellation",
                            Price = 249.99m,
                            Type = "Over-Ear",
                            Weight = "296 grams",
                            Wireless = true
                        },
                        new
                        {
                            Id = new Guid("aa328d09-ba2c-4bfd-9620-ae973dac2007"),
                            BatteryLife = "N/A",
                            Color = "Blue",
                            Description = "Professional-grade studio monitor headphones with exceptional clarity, sound isolation, and durability.",
                            ImageFileName = "Audio-Technica_ATH-M50x.webp",
                            Manufacturer = "Audio-Technica",
                            Mic = false,
                            Name = "Audio-Technica ATH-M50x",
                            NoiseCancellationType = "None",
                            Price = 149m,
                            Type = "Over-Ear",
                            Weight = "285 grams",
                            Wireless = false
                        },
                        new
                        {
                            Id = new Guid("b9e754f2-1d55-42e5-bf9d-83b2b4ac7cb3"),
                            BatteryLife = "Up to 22 hours",
                            Color = "Red",
                            Description = "Stylish on-ear headphones with active noise cancellation, impressive sound quality, and up to 22 hours of battery life.",
                            ImageFileName = "Beats_Solo_Pro.jpeg",
                            Manufacturer = "Beats",
                            Mic = true,
                            Name = "Beats Solo Pro",
                            NoiseCancellationType = "Active Noise Cancellation",
                            Price = 299.95m,
                            Type = "On-Ear",
                            Weight = "267 grams",
                            Wireless = true
                        },
                        new
                        {
                            Id = new Guid("e088cba7-f5f5-4da8-873c-56c6a79f5190"),
                            BatteryLife = "N/A",
                            Color = "Black",
                            Description = "Premium open-back headphones known for their outstanding sound quality, luxurious comfort, and high-quality materials.",
                            ImageFileName = "Sennheiser_HD_800_S.jpg",
                            Manufacturer = "Sennheiser",
                            Mic = false,
                            Name = "Sennheiser HD 800 S",
                            NoiseCancellationType = "Passive Noise Cancellation",
                            Price = 1499.95m,
                            Type = "Over-Ear",
                            Weight = "330 grams",
                            Wireless = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
